# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-11 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Active',
        ),
    ]
